[package]
name = "classical_ciphers"
version = "0.1.0"
authors = ["Karan Mungra <klmungra23@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.3"